import React from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Provider } from '@/context/providers';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100">
            <div className="container mx-auto px-4 py-8">
              {/* Header */}
              <div className="text-center mb-12">
                <h1 className="text-4xl font-bold my-10">Reactify-Week</h1>
                <p className="text-lg text-gray-600 max-w-3xl mx-auto">
                  Discover amazing activities for every day of the week. Select your favorites and
                  build your perfect schedule. Our AI-powered system generates smart tags and
                  personalized recommendation cards to help you find the best activities tailored
                  just for you.
                </p>
              </div>
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
